# Generated by Django 5.1.7 on 2025-04-21 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playScene', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='num2',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='num1',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='flies',
        ),
        migrations.CreateModel(
            name='AdditionProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playScene.problem')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_for_addition_problem', to='playScene.fly')),
                ('flies', models.ManyToManyField(related_name='flies_for_addition_problem', to='playScene.fly')),
            ],
            bases=('playScene.problem',),
        ),
        migrations.CreateModel(
            name='PlaceValueProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playScene.problem')),
                ('num', models.IntegerField()),
                ('place_to_check', models.CharField(choices=[('O', 'Ones'), ('T', 'Tens'), ('H', 'Hundreds')], default='O', max_length=1)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_for_place_value_problem', to='playScene.fly')),
                ('flies', models.ManyToManyField(related_name='flies_for_place_value_problem', to='playScene.fly')),
            ],
            bases=('playScene.problem',),
        ),
        migrations.CreateModel(
            name='SubtractionProblem',
            fields=[
                ('problem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='playScene.problem')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer_for_subtraction_problem', to='playScene.fly')),
                ('flies', models.ManyToManyField(related_name='flies_for_subtraction_problem', to='playScene.fly')),
            ],
            bases=('playScene.problem',),
        ),
    ]
